version: "3.8"

networks:
  netlog:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  kaynak:
    container_name: originator # Günlük üretene ingiliçce originator diyolla
    volumes:
      - ./kaynak/cron-tablom:/etc/cron.d/cron-tablom
      - ./kaynak/calistir.sh:/root/calistir.sh
      - ./kaynak/mirror.sh:/root/mirror.sh
      - ../etc-crontab/etc/rsyslog.d/50-default.conf:/etc/rsyslog.d/50-default.conf
    build: 
      context: ../
      dockerfile: Dockerfile
    image: cemt/cron-rsyslog
    command: sh -c "service rsyslog start && service cron start && tail -f /dev/null"
    logging:
      driver: loki
      options:
        loki-url: "http://10.5.0.3:3100/loki/api/v1/push"
    networks:
      netlog:
        ipv4_address: 10.5.0.2


  # Loki günlük toplayıcısı
  loki:
    container_name: loki
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100 
    image: grafana/loki
    # loki konteyneri günlük dosyaları oluşturacak ve bu günlükleri
    # json-file sürücüsüyle en çok 10MB dosya büyüklüğüne ulaşacak 5 günlük dosyası saklar
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      netlog:
        ipv4_address: 10.5.0.3


  # will be available at http://127.0.0.1:3000
  # default credentials: admin/admin
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.2
    networks:
      netlog:
        ipv4_address: 10.5.0.4
    ports:
      - "3000:3000"
    volumes:
      # directory must be created first, with uid:gid 472:472
      #- ./grafana/lib:/var/lib/grafana
      # automatically configure the loki datasource
      - ./grafana/provisioning/:/etc/grafana/provisioning/
