version: "3.8"

services:
  kaynak:
    container_name: originator # Günlük üretene ingiliçce originator diyolla
    volumes:
      - ./kaynak/cron-tablom:/etc/cron.d/cron-tablom
      - ./kaynak/calistir.sh:/root/calistir.sh
    build: 
      context: ../
      dockerfile: Dockerfile
    image: cemt/cron-rsyslog
    command: tail -f /dev/null
    logging:
      driver: loki
      options:
        loki-url: "https://admin:admin@loki/loki/api/v1/push"


  # Loki günlük toplayıcısı
  loki:
    container_name: loki-collector
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100 
    image: grafana/loki


  # will be available at http://127.0.0.1:3000
  # default credentials: admin/admin
  grafana:
    image: grafana/grafana:9.2.2
    ports:
      - "3000:3000"
    volumes:
      # directory must be created first, with uid:gid 472:472
      - ./grafana/lib:/var/lib/grafana
      # automatically configure the loki datasource
      - ./grafana/provisioning/:/etc/grafana/provisioning/
