version: "3.8"

services:
  kaynak:
    container_name: originator # Günlük üretene ingiliçce originator diyolla
    volumes:
      - ./kaynak/cron-tablom:/etc/cron.d/cron-tablom
      - ./kaynak/calistir.sh:/root/calistir.sh
    build: 
      context: ../
      dockerfile: Dockerfile
    image: cron:rsyslog
    command: cron -f

# Loki günlük toplayıcısı
  loki:
    container_name: loki-collector
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100 
    image: grafana/loki
