version: "3.8"

services:
  ccc:
    container_name: ccc
    volumes:
      - ./conf:/etc/crontab
      - ./ilk.sh:/root/ilk.sh
      - ./iki.sh:/root/iki.sh
    build:
      context: ../
      dockerfile: Dockerfile
    image: cemt/cron-rsyslog
    command: tail -f /dev/null
